ModelosBundle\Entity\Contacto:
    type: entity
    table: contacto
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        comentario:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
    lifecycleCallbacks: {  }
