ModelosBundle\Entity\Juegos:
    type: entity
    table: juegos
    indexes:
        id_subcategoria:
            columns:
                - id_subcategoria
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        imagen:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    manyToOne:
        idSubcategoria:
            targetEntity: Subcategoria
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_subcategoria:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
