apuestas_insertar:
    path:     /insertar-apuesta
    defaults: { _controller: ApuestasBundle:Default:insertarApuesta }
apuestas_update:
  path:     /update-apuesta
  defaults: { _controller: ApuestasBundle:Default:updateApuesta }
